### ISSUE TITLE
Additions?

### ISSUE THREAD

**Issue by brainwane** [mhoye/minimum-viable-user-stories#2]
I'm not quite sure whether this is meant to be a locked-to-others'-PRs repo or not; are suggestions welcome? (For instance, would it be ok to add a link to http://exple.tive.org/blarg/2016/10/12/minimum-viable-basic-human-decency/ to the README for context, and are additional user stories welcome?)

**Comment by mhoye** [comment]
Almost the six year anniversary of this, but yes, changes are welcome.
